### ISSUE TITLE
Add Postgres port forwarding

### ISSUE THREAD

**Issue by chapmandu** [nickjj/docker-rails-example#42]
Add Postgres port forwarding to be able to connect to the development db using a GUI.

eg:
#### .env
```
export POSTGRES_PORT_FORWARD=54320
```

#### docker-compose.yml
```
services:
  postgres:
    ...
    ports:
      - "${POSTGRES_PORT_FORWARD:-54320}:${POSTGRES_PORT:-5432}"
```
